---
# tasks file for role/nginx_server
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: true
  become: yes

- name: Configure Nginx
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx
