apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-dep
  template:
    metadata:
      labels:
        app: prod-dep
    spec:
      containers:
      - name: prod-dep
        image: yashparmar04/prod-dep:latest
        ports:
        - containerPort: 80
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-prod
spec:
  selector:
    app: prod-dep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
